### ISSUE TITLE
你这不对啊哥哥

### ISSUE THREAD

**Issue by Jinspang** [angelk727/mir2#11]
你看，以前的登陆器有800*600的选项，这后来去掉了，最小选项就是1024，你怎么吧第一启动画面改成800*600了啊？登陆器勾选1024，第一画面却是800这不符合常理啊。

里面那个绝技盒也用不了，看你之前的更新说明文件，和现在的端对比多了很多内容应该，多的什么？功能做到哪里了？这些都不得而知，现在只能看很早以前你发的那个更新内容的文本，都不知道更新到什么功能位置了啊，

还有我看哥哥好像要按照HF原版去做呀？那能不能加上服务器选择这个   第一启动 画面呢？ 我看LIB里就有这些图片怎么没人写这个功能啊？ 按道理第一画面是选择服务器，选择后第二画面才是输入账号，把这个做上吧，10个区，分别对应10个IP和端口，分别对应10个更新地址或者文件名。

还有那个英雄，攻击方式应该是自由攻击，反击，跟随，和固定攻击吧？ 现在这个攻击和自定模式是一样的，这个自定假设是自由攻击，那么攻击他应该是固定攻击，也就是英雄不乱跑，站在固定位置攻击才对啊，现在这俩模式都是自主攻击乱跑的。

还有那个邮寄，怎么贴邮票的  √  他不显示啊？也没反应，应该贴邮票后  下面变成五个格子才对，你现在什么反应都没有，还有邮票，放在背包里，按住SHIFT，点鼠标左键好像。 他就消失了，，，，怎么和药水一样还能吃掉？

最后总结啊哥哥，能不能和以前一样付一个更新说明，好知道更新了什么内容了呀，更新到哪里了，现在都是一头雾水。。。。

![QQ图片20240620145242](https://github.com/angelk727/mir2/assets/172731882/a9046fd6-a604-4988-94b4-e91aad725b8f)

**Comment by cnksss** [comment]
的确，很多功能在后来同步的更新后变回C#原版的了。：（

**Comment by Jinspang** [comment]
这位哥哥好像断更了啊......不知道怎么回事

**Comment by cnksss** [comment]
没有吧，很多版本，就这位大佬的是无限接近韩的，所以也在默默关注，可惜自己不懂VS，所以智能默默等大佬更新了。

**Comment by cnksss** [comment]
作者应该也有其它事情要做，耐心等就好

**Comment by cnksss** [comment]
最后更新貌似弓箭手的技能也有问题了。新手行会的问题我也没弄明白新建角色为什么加入不了。
