### ISSUE TITLE
@GIVESKILL 命令失效

### ISSUE THREAD

**Issue by Jinspang** [angelk727/mir2#12]
@GIVESKILL   攻杀剑术   3
@GIVESKILL   攻杀剑术 
@GIVESKILL   小魔女  攻杀剑术   3
@GIVESKILL   小魔女  攻杀剑术

找到问题了 ，的用英文的，这个问题应该解决汉化了他

**Comment by Jinspang** [comment]
找到问题了，源码里面的技能没汉化成中文  英文就可以了。
@GIVESKILL Fencing 3                                      基本剑术 3
@GIVESKILL Slaying 3                                       攻杀剑术 3
@GIVESKILL Thrusting 3                                   刺杀剑术 3
@GIVESKILL HalfMoon 3                                  半月弯刀 3
@GIVESKILL ShoulderDash 3                            野蛮冲撞 3
@GIVESKILL TwinDrakeBlade 3                         双龙斩 3
@GIVESKILL Entrapment 3                               捕绳剑 3
@GIVESKILL FlamingSword 3                           烈火剑法 3
@GIVESKILL LionRoar 3                                   狮子吼 3
@GIVESKILL CrossHalfMoon 3                         狂风斩 3
@GIVESKILL BladeAvalanche 3                        空破闪 3
@GIVESKILL ProtectionField 3                         护身气幕 3
@GIVESKILL Rage 3                                        剑气爆 3
@GIVESKILL CounterAttack 3                         天务 3
@GIVESKILL SlashingBurst 3                           日闪 3
@GIVESKILL Fury 3                                         血龙剑法 3
[@Wizard]
#ACT
GIVESKILL FireBall 3                                     火球术 3
GIVESKILL Repulsion 3                                 抗拒火环 3
GIVESKILL ElectricShock 3                            诱惑之光 3
GIVESKILL GreatFireBall 3                             大火球 3
GIVESKILL HellFire 3                                     地狱火 3
GIVESKILL ThunderBolt 3                              雷电术 3
GIVESKILL Teleport 3                                   瞬息移动 3
GIVESKILL FireBang 3                                    爆裂火焰 3
GIVESKILL FireWall 3                                     火墙 3
GIVESKILL Lightning 3                                    疾光电影 3
GIVESKILL FrostCrunch 3                               寒冰掌 3
GIVESKILL ThunderStorm 3                                地狱雷光 3
GIVESKILL MagicShield 3                                 魔法盾 3
GIVESKILL TurnUndead 3                                  圣言术 3
GIVESKILL Vampirism 3                                    噬血术 3
GIVESKILL IceStorm 3                                      冰咆哮 3
GIVESKILL FlameDisruptor 3                             灭天火 3
GIVESKILL Mirroring 3                                      分身术 3
GIVESKILL FlameField 3                                  火龙气焰 3
GIVESKILL Blizzard 3                                       天霜冰环 3
GIVESKILL MagicBooster 3                               深延术 3
GIVESKILL MeteorStrike 3                                  流星火雨 3
GIVESKILL IceThrust 3                                       冰焰术 3
[@Taoist]
#ACT
@GIVESKILL Healing 3                               治愈术 3


@GIVESKILL Poisoning 3                          施毒术 3
@GIVESKILL SpiritSword 3                         精神力战法 3
@GIVESKILL SoulFireBall 3                        灵魂火符3
@GIVESKILL SummonSkeleton 3                召唤骷髅 3
@GIVESKILL Hiding 3                              隐身术 3
@GIVESKILL MassHiding 3                      集体隐身术 3
@GIVESKILL SoulShield 3                          幽灵盾 3
@GIVESKILL Revelation 3                         心灵启示 3
@GIVESKILL BlessedArmour 3                 神圣战甲术 3
@GIVESKILL EnergyRepulsor 3                   气功波 3
@GIVESKILL TrapHexagon 3                   困魔咒 3
@GIVESKILL Purification 3                        净化术 3
@GIVESKILL MassHealing 3                  群体治疗术 3
@GIVESKILL Hallucination 3                      迷魂术 3
@GIVESKILL UltimateEnhancer 3           无极真气 3
@GIVESKILL SummonShinsu 3                   召唤神兽 3
@GIVESKILL Reincarnation 3                     苏生术 3
@GIVESKILL SummonHolyDeva 3                精魂召唤术 3
@GIVESKILL Curse 3                                    诅咒术 3
@GIVESKILL Plague 3                                 烦恼 3
@GIVESKILL PoisonCloud 3                      毒云 3
@GIVESKILL EnergyShield 3                          先天气功 3
[@Assassin]
#ACT
@GIVESKILL FatalSword 3                          绝命剑法 3                         
@GIVESKILL DoubleSlash 3                         风剑术 3
@GIVESKILL Haste 3                                     体迅风 3
@GIVESKILL FlashDash 3                              拔刀术 3
@GIVESKILL LightBody 3                               风身术 3
@GIVESKILL HeavenlySword 3                     迁移剑 3
@GIVESKILL FireBurst 3                               烈风击 3
@GIVESKILL Trap 3                                       捕缚术 3
@GIVESKILL PoisonSword 3                       猛毒剑气 3
@GIVESKILL MoonLight 3                        月影术 3
@GIVESKILL MPEater 3                          吸气 3
@GIVESKILL SwiftFeet 3                          轻身步 3
@GIVESKILL DarkBody 3                           烈火身 3
@GIVESKILL Hemorrhage 3                        血风击 3
@GIVESKILL CrescentSlash 3                      月华乱舞3
[@Archer]
#ACT
@GIVESKILL Focus       3                            必中闪 
@GIVESKILL StraightShot 3                         天日闪 3
@GIVESKILL DoubleShot 3                         无我闪 3
@GIVESKILL ExplosiveTrap 3                      爆炸陷阱 3
@GIVESKILL DelayedExplosion 3              爆闪 3
@GIVESKILL Meditation 3                           气功术 3
@GIVESKILL BackStep 3                            风弹步 3
@GIVESKILL ElementalShot 3                    万斤闪 3
@GIVESKILL Concentration 3                      气流术 3
@GIVESKILL ElementalBarrier 3                    金刚术 3
@GIVESKILL SummonVampire 3                   吸血蜘蛛 3
@GIVESKILL VampireShot 3                     血魔闪 3
@GIVESKILL SummonToad 3                    痹魔阱 3
@GIVESKILL PoisonShot 3                             毒魔闪 3
@GIVESKILL CrippleShot 3                       邪爆闪 3
@GIVESKILL SummonSnakes 3                 蛇柱阱 3
@GIVESKILL NapalmShot 3                       血龙闪 3
@GIVESKILL OneWithNature 3                  血龙闪-秘籍 3
@GIVESKILL  Stonetrap 3       地柱钉

**Comment by angelk727** [comment]
[@Warrior]
#IF
CHECKCLASS 战士
#ACT
GIVESKILL 1 3
GIVESKILL 2 3
GIVESKILL 3 3
GIVESKILL 4 3
GIVESKILL 5 3
GIVESKILL 6 3
GIVESKILL 7 3
GIVESKILL 8 3
GIVESKILL 9 3
GIVESKILL 10 3
GIVESKILL 11 3
GIVESKILL 12 3
GIVESKILL 13 3
GIVESKILL 14 3
GIVESKILL 15 3
GIVESKILL 16 3
GIVESKILL 17 3
技能书的外观图像号
