### ISSUE TITLE
Prguse 缺失 2447 素材

### ISSUE THREAD

**Issue by cnksss** [angelk727/mir2#13]
该素材为游戏“元宝”奖励素材

**Comment by sddzrxh** [comment]
你会翻译韩文吗？大佬给我一个韩版Title的LIB按钮文件，大部分位置和现在的一样，我不懂韩文，网上翻译也不对，你要能翻译只需要按序号把名字给我打出来，按钮我来做，然后发给大佬，让大佬按照新版的按钮来做

从0开始，例如：1仓库    2什么   3 什么    我就按照编号来做。

你要不懂韩文也是网上翻译就算了，很多翻译出来都是错误的，能翻译留个联系方式我发你，你翻译过来我来做按钮

**Comment by sddzrxh** [comment]
他这个不一样，里面多了很多东西我看着，而且没重复，没删减，就按照官方的编码走的好像，如果用别人的还做这个干啥，，，，

**Comment by cnksss** [comment]
是的，也是我关注作者的原因，你说的问题其实在某种意义上能解决，建议你去韩服数据网站看看，那里有你想要的东西

**Comment by sddzrxh** [comment]
邮件贴邮票那个按钮你那里有问题吗？我这里点他没反应

**Comment by cnksss** [comment]
这个版本貌似没有修复，我这有其他的版本已经修复了的。就是解锁格子的。

**Comment by sddzrxh** [comment]
什么版本的？是源码的吗
