### ISSUE TITLE
全屏关闭后登陆器挂起

### ISSUE THREAD

**Issue by sddzrxh** [angelk727/mir2#17]
这个问题我看老外说是老问题了，早解决了，怎么这个端还是有这个问题，全屏退出游戏后全屏窗口仍然存在，登陆器挂起状态，桌面都点不了、

**Comment by sddzrxh** [comment]
今天看老外说CTRL+A 按住别动  2两秒以上掉线，测试了一下还真是，说是大量数据包....

**Comment by angelk727** [comment]
CTRL+A 、X、CTRL+H 等按住2秒都会掉线。这的确是个问题。这次更新只在客户端做了修改杜绝了这个问题，服务端修改就交给.....至于全屏无法退出的问题是存在的。如果你有空把修复的代码拉过来。记得只要代码，不要放马哟！

**Comment by sddzrxh** [comment]
我哪会写....我在学习中....

![image](https://github.com/angelk727/mir2/assets/42303818/212b619c-634c-4fad-869b-9ae9651f2ebf)
