### ISSUE TITLE
道士英雄会被自己召唤出来的宝宝打死。。。

### ISSUE THREAD

**Issue by cnksss** [angelk727/mir2#20]
RT。

**Comment by sddzrxh** [comment]
什么宝宝？我这怎么没问题？

**Comment by angelk727** [comment]
[Crystal](https://github.com/Suprcode/Crystal)近期修改中有很多问题，英雄部分这里我只恢复了弓箭英雄和修改了英雄攻击模式的控制。至于道士英雄在韩官方是不能召唤的，所有我也没有测试过。你可以去Crysta那里反应问题

**Comment by sddzrxh** [comment]
我测试了没他说的问题，不知道他怎么操作的，具体也不说清楚。

**Comment by angelk727** [comment]
我在网盘更新了20240710Mir2Server服务端，参考测试
