### ISSUE TITLE
超级大问题啊？

### ISSUE THREAD

**Issue by sddzrxh** [angelk727/mir2#21]
我滴妈呀，我这还闷头测试，刚发现地图刷怪不全，有的地图甚至没有。

最主要是一点爆率都没有啊.............你这个服务端是按照那个弄的啊？有没有刷怪和爆率参照啊，
没有的话一个地图一个地图的对比刷怪。。。。在一个怪一个怪的写爆率.........这工程.............

我这寻思找别人的端抄刷怪和爆率吧，很多怪物名字也不对，还要一个个对比.................

天啊...........   有没有完整的刷怪和爆率呀？

**Comment by cnksss** [comment]
[怪物数据.xlsx](https://github.com/user-attachments/files/16186341/default.xlsx)
大兄弟，有时候需要自己弄的，作者先把服务器类的东西做好才是最主要的，否则再怎么完整，bug一堆也是愁人的，这个文件就是怪物数据，可以根据自己的喜好去调整，刷怪跟爆率这个仁者见仁，智者见智，如果放在国内肯定是快餐服，没见过哪个仿韩的服务器超过百人，而且能长久的，鸡服那种早就脱离了韩版路线了。

**Comment by cnksss** [comment]
![屏幕截图 2024-07-12 102137](https://github.com/user-attachments/assets/a636caa0-4dc0-449c-a6d5-9f3d1496790a)
爆率的你可以参考这样的设置，也可以把boss或者极品怪设置成你想要的单个爆率文件

**Comment by sddzrxh** [comment]
> 爆率的你可以设置成分组，小怪一组，boss或者极品怪设置成你想要的单个爆率文件

能不能留个联系？远程帮我看看？

**Comment by cnksss** [comment]
![屏幕截图 2024-07-13 103242](https://github.com/user-attachments/assets/8c067df5-047a-43bb-a25a-77f71d632d05)
参考这样子来设置，这个需要很长时间的调整，费时费力，我也没有做好，等这个版本弄好后我也把爆率相关文件共享出来就是了

**Comment by sddzrxh** [comment]
参考这样子来设置，这个需要很长时间的调整，费时费力，我也没有做好，等这个版本弄好后我也把爆率相关文件共享出来就是了

那我等你共享吧，你这个文件别人给我了，我也不会搞
