### ISSUE TITLE
收集BUFF资料

### ISSUE THREAD

**Issue by angelk727** [angelk727/mir2#22]
现征集韩版传奇BUFF。请将游戏BUFF的属性及BUFF图标，有的BUFF会有人物特效。请一并告知。

**Comment by cnksss** [comment]
这个有点难度了，国内在水晶论坛活跃的就是一个叫飞机的哥们，不知道他有没有，我问下他。
我手里有的版本基本上都是改的面目全非的了。

**Comment by cnksss** [comment]
看了下mirdb网站里貌似没有buff相关资料

**Comment by cnksss** [comment]
[BuffIcon.zip](https://github.com/user-attachments/files/16200687/BuffIcon.zip)
buff相关的属性我找人问问，这个文件是buff图标

**Comment by cnksss** [comment]
[韩服数据库汉化文件.zip](https://github.com/user-attachments/files/16200699/default.zip)
![676e076f-db19-45fd-9309-881bfd91fec7](https://github.com/user-attachments/assets/5656a8ed-6411-42bf-aa73-dec9571d372f)
这是之前整理的数据汉化，虽然不是很完善，但也可以作为参考

**Comment by sddzrxh** [comment]
这个事情得找长期玩韩服得问才行，而且还得精通的。飞机也不一定精通。建议去MIR2DB数据库去看看

**Comment by sddzrxh** [comment]
看看这个端的BUFF很全，天气效果也很逼真，下雨，下雪，雾天都特别逼真。
功能也很全面。感觉可以借鉴一下。

服务端：https://www.123pan.com/s/eYRDjv-kBme.html提取码:vVCq
客户端：https://www.123pan.com/s/eYRDjv-oBme.html提取码:VAhF

**Comment by cnksss** [comment]
> 看看这个端的BUFF很全，天气效果也很逼真，下雨，下雪，雾天都特别逼真。 功能也很全面。感觉可以借鉴一下。
> 
> 服务端：[https://www.123pan.com/s/eYRDjv-kBme.html提取码:vVCq](https://www.123pan.com/s/eYRDjv-kBme.html%E6%8F%90%E5%8F%96%E7%A0%81:vVCq) 客户端：[https://www.123pan.com/s/eYRDjv-oBme.html提取码:VAhF](https://www.123pan.com/s/eYRDjv-oBme.html%E6%8F%90%E5%8F%96%E7%A0%81:VAhF)

你这个是不紧张的代码，水晶分支JEV（就是现在在弄mir1，mir4，zircon的作者）找不紧张要的和尚代码，这个版本已经是脱离了原来水晶的路线了，现在最新的客户端跟服务器更新到6月（共享出来的），手机版本也更新了好几代了

**Comment by cnksss** [comment]
[韩2所有怪物数据7.26.xlsx](https://github.com/user-attachments/files/16402115/2.7.26.xlsx)
BUFF类的数据很难收集，问了一圈人了，没有做过系统的统计。。。慢慢来吧
