### ISSUE TITLE
这个改掉吧.

### ISSUE THREAD

**Issue by Jinspang** [angelk727/mir2#26]
CheckVersion=False  版本检查改成关闭。
AllowStartGame=True 允许进入游戏改成开启。
每次生成Setup都要重新勾选一边。

配方合成界面缺少一个删除按钮，有利于新接触的玩家操作，不用找文件夹单独删除了。

账户界面右下角最后一行不是【职位】   他应该是 状态，那里内容显示是在线：离线：删除：

新加的角色界面感觉毫无意义，只能看不能操作，如果在后面增加一个状态显示就好了
其实我一直没搞明白，账户设置内有个显示离线在线和删除，把这个已删除的角色的删除改为离线是不是就是恢复了已删除的角色？
那这样登录时在人物界面下面那个“恢复角色”按钮是不是可以实现恢复角色了？
![image](https://github.com/user-attachments/assets/c50c4c86-587c-48cb-ba11-96c53917f79e)

聊天框正常模式下显示4行文字，最后一行文字会遮挡输入框1像素。
武器精炼建议增加一个次数限制，现在是无限次数精炼不适合仿盛大版本。

**Comment by angelk727** [comment]
CheckVersion=False 版本检查改成关闭。
AllowStartGame=True 允许进入游戏改成开启 这两个设置基本属于防蠢功能，你仔细想。

配方合成这个不要说再增加个删除按钮 ，我都想把新添加 屏蔽。
【职位】 这个问题已经采纳 并修改完成。
新加的角色 我想他是不是想以后扩展些什么，提前做些准备。
聊天我改过后来又随水晶走 没太大影响
精炼好远古的问题 我记得有设置 7次 还是 9次  跟祝福油都有限制。
