### ISSUE TITLE
end

### ISSUE THREAD

**Issue by sddzrxh** [angelk727/mir2#3]
end

**Comment by angelk727** [comment]
是的 客户端增加了Weather.Lib 文件。但我的Weather.Lib中只添加一个雾的图片

**Comment by sddzrxh** [comment]
> 是的 客户端增加了Weather.Lib 文件。但我的Weather.Lib中只添加一个雾的图片

好的我去下载新的，还有个问题大佬，就是生成的时候登陆器文件要生成一大堆文件，能否给他集成到里面  减少外露那么多文件啊？
