### ISSUE TITLE
大佬你这新版本怎么和之前源码不一样了哦

### ISSUE THREAD

**Issue by Jinspang** [angelk727/mir2#42]
英雄也不行了，27及就升不动了，40级就满级了。
中途的解锁也没有了  按道理不是 30  40  50  60  什么的解锁卷吗

你这改的没法和您同步啊.......

**Comment by angelk727** [comment]
![level40](https://github.com/user-attachments/assets/07a89600-e811-4957-8616-a1a1fa7243b4)

**Comment by Jinspang** [comment]
我吧服务器告诉你  一起研究吧大佬？
