### ISSUE TITLE
怎么解决.........

### ISSUE THREAD

**Issue by Jinspang** [angelk727/mir2#43]
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277: 发现无法解析的“WindowsBase”的不同版本之间存在冲突。
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277: “WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”与“WindowsBase, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”之间存在冲突。
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:     已选择“WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”，因为它是主版本而“WindowsBase, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”不是。
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:     依赖于“WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”[C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.11\ref\net8.0\WindowsBase.dll]的引用。
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:         C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.11\ref\net8.0\WindowsBase.dll
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:           导致引用“C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.11\ref\net8.0\WindowsBase.dll”的项目文件项 Include 特性。
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:             C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.11\ref/net8.0/WindowsBase.dll
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:     依赖于或已统一到“WindowsBase, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”[] 的引用。
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:         C:\Users\top\.nuget\packages\microsoft.web.webview2\1.0.2849.39\lib_manual\net5.0-windows10.0.17763.0\Microsoft.Web.WebView2.Wpf.dll
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:           导致引用“C:\Users\top\.nuget\packages\microsoft.web.webview2\1.0.2849.39\lib_manual\net5.0-windows10.0.17763.0\Microsoft.Web.WebView2.Wpf.dll”的项目文件项 Include 特性。
6>D:\VS2022\A\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:             C:\Users\top\.nuget\packages\microsoft.web.webview2\1.0.2849.39\buildTransitive\..\\lib_manual\net5.0-windows10.0.17763.0\Microsoft.Web.WebView2.Wpf.dll

**Comment by angelk727** [comment]
要么你安装升级 net8.0 要么我降低。你给个选择

**Comment by Jinspang** [comment]
我安装8.04了
