### ISSUE TITLE
关于更新！！！

### ISSUE THREAD

**Issue by Jinspang** [angelk727/mir2#45]
我在服务器的C盘内做了一个名为  gengx  的文件夹。
然后搭建了FTP。
源码内更新地址是不是填写     ftp://我的IP/gengx/    这个地址啊？

然后吧需要更新的文件放到服务器的   gengx  文件夹内。

然后用工具直接创建列表，其他的不用管了对吗？

![image](https://github.com/user-attachments/assets/df2f2772-b0e3-4b54-8308-9c676062d237)

**Comment by angelk727** [comment]
我正研究源码病毒的问题

**Comment by Jinspang** [comment]
> 我正研究源码病毒的问题

好吧，上次我问您一次怎么搞更新了，，，我一直没弄明白怎么搞。。。你有时间了在回复我把

**Comment by Jinspang** [comment]
我实在弄不了了   地址有了   又不能生成GZ了
![image](https://github.com/user-attachments/assets/5db2a873-0c4e-4034-883e-ec81d41f2725)

**Comment by Jinspang** [comment]
还是不行  重新部署了FTP 还是不行
![image](https://github.com/user-attachments/assets/feb8ade8-f5ed-4b76-92a5-fde7e34b4c1f)

**Comment by Jinspang** [comment]
现在可以更新了，但是一更新就提示这个错误怎么回事啊？最后提示问题太多了不显示了。

![image](https://github.com/user-attachments/assets/219f5744-47cd-494f-a408-ee12ebacaff7)

**Comment by angelk727** [comment]
你的 PList.gz 是怎样编辑的？是用 的 http、https、 ftp 那个协议呢？

**Comment by Jinspang** [comment]
我服务器部署的IIS，端口80.默认网站目录是WWW对吧。
然后我把FTP目录也设置成网站同一个目录，也是WWW目录，FTP端口21.
源码内你写的我没动，我只改成了外网的IP。然后我把WWW里放了图1那一套，我有在WWW内建立了mir2/cmir/patch/
然后又复制到 patch 文件夹里一套。
 
然后用AutoPatcherAdmin  生成  PList.gz   的

**Comment by Jinspang** [comment]
> 网站的MIME 类型用的是.gz application/gzip 还是 x-gtar ?

 这个我不懂啊，你上阿里云https://www.aliyun.com/activity/1111/2024?utm_content=se_1019418816 登录吧二维码截图发来我刷新等你，然后我扫码你上去看看？ 
服务器登录
![image](https://github.com/user-attachments/assets/861bb765-0196-4428-91a3-86e001a8f77d)

**Comment by angelk727** [comment]
不用了 请删除 。是部分更新还是全部更新都有问题呢？还没用回答我 。现在我回答你些你的问题 ，关于弓箭手位置 的问题，我还专门做了悬浮提示但凡那你多看一眼都不会有问题。任务栏其实根本不会超出20个任务没用必要设置实体按钮。最后问你我的源代码有病毒吗？

**Comment by Jinspang** [comment]
> 
就那个DX错误，别的没事，n你看看全是DX
![image](https://github.com/user-attachments/assets/f29e77ea-027f-4f9a-a47e-947776dc0787)

**Comment by angelk727** [comment]
那应该很好解决
