### ISSUE TITLE
LEVEL

### ISSUE THREAD

**Issue by Jinspang** [angelk727/mir2#46]
这个BUG之前不是修复了吗？怎么又更新回去了？

GM号@CREATEGUILD 创建行会后     @level  等级。 行会就解散了。

破天魔龙被攻击时声音对吗？我没玩过官服。铛铛铛的，是打铁的声音。

**Comment by angelk727** [comment]
行会就解散 的问题我在 https://github.com/angelk727/mir2/issues/1 中集中回复了
破天魔龙的声音 请告诉我正确的声音文件名称 。
