### ISSUE TITLE
龟王放技能会卡 猪和牛打起来也很卡

### ISSUE THREAD

**Issue by benfang928** [angelk727/mir2#49]

**Comment by angelk727** [comment]
请详细说明 我会修复

**Comment by benfang928** [comment]
> 请详细说明 我会修复

你召唤个龟王出来打下就知道了 龟王放技能的时候很卡

**Comment by xc1258** [comment]
攻击猪牛的时候也会卡，原因是猪牛的声音文件和别的数率不一致。

**Comment by trek600** [comment]
这两天恰好发现了这个问题,原因是特效中特效开始事件的处理有问题.
对于龟王,在释放技能的时候发出特效,特效的设置中设置了一个特效开始事件,为播放一个音乐.
而客户端对于所有的特效处理都是基于时间间隔检测的,但是特效的开始事件监测存在问题,如下图

![Image](https://github.com/user-attachments/assets/7665bb8f-8aab-4b42-a70a-7c5ee1a73961)
根据上面代码,只要是特效的动画序列帧的帧数为1,就触发一次特效开始的事件处理.
在客户端循环之中,就会不断进行特效处理,由于不到下一帧的处理时间,因此上面这个事件的处理次数根本不是1,而是在这个周期内客户端游戏循环次数.
回到龟王放技能的时候,它的逻辑是随机播放4到8个特效,此时,这段时间内就会大量播放音乐.

![Image](https://github.com/user-attachments/assets/c4dde1aa-d840-4041-a2b6-e56211b95479)
我们再找到客户端卡顿的日志文件中,发现就是音效混合的时候超出了最大数量,默认是1024个音效的最大缓存量,由此可以确定上面的推断--->,问题就出现在特效的开始事件处理不当,实际短时间内大量循环产出大量事件,进而出现大量音效播放,最终超过默认的最大数量,造成客户端异常,因此客户端就卡顿了.

修改方式:
我找到了客户端所有的使用特效开始事件的地方,发现没有任何一个地方是循环特效(特效一次播放完毕,重新再播放,直到满足次数或者特效的结束时间). 因此,我对于播放事件定义的语义不能完全确定.
1.就仅仅在特效首次播放的时候执行一次事件
2.对于循环的特效,每个循环都执行一次事件.
我更倾向于第二种.
这样,对于问题的修复,我们只要修改帧数的检测即可.
默认代码是先执行事件的处理,然后再检测时间是否符合.
直接将这两个顺序换一下,首先检测时间,然后再执行开始事件的处理即可.
