### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by sddzrxh** [angelk727/mir2#5]
下面有俩图片你看看，
数据库CSV第一列是怪物名称，第二列大部分是英文，一小部分是中文，
中文的第二列和第一列名称一样。我直接用工具吧第一列的中文怪物名整体复制到第二列。
导入时没错，导入完出错了，第二列不显示，我在源码里看了看是不是汉化源码呀？

我可以整列整列的复制粘贴，你需要我复制完的吗？需要的话我就传盘里。

这个网站图片刷出来的很慢，你慢慢刷看看
![QQ图片20240526193455](https://github.com/angelk727/mir2/assets/42303818/7dc78e60-d6f3-42b7-a26b-eb074f47a20f)
![QQ图片20240526193540](https://github.com/angelk727/mir2/assets/42303818/bf710413-0f09-4074-bd49-cf4b00effd46)

**Comment by angelk727** [comment]
我用的是 TXT格式不是CSV格式 第二列是调用客户端怪物的.LIB 数据。我不明白你要做什么？

**Comment by sddzrxh** [comment]
我意思这个数据库怪物名还有不少是英文呢，他是不是应该和怪物名统一的名字啊？还是本来就要英文的？我看里面有些一些你汉化完了，大部分还是英文 ，这个一个一个改太麻烦，我意思怪物名和数据库怪物名如果统一的话，我可以整列复制过去，TXT无法整列复制。如果这样简单点我可以帮你都改了，如果这边本来就是英文那就当我没说。。。。











哒哒哒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "angelk727/mir2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月27日(星期一) 中午1:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [angelk727/mir2] 数据库问题 (Issue #5)





 
我用的是 TXT格式不是CSV格式 第二列是调用客户端怪物的.LIB 数据。我不明白你要做什么？
