### ISSUE TITLE
刺客武器特效素材库加载错误

### ISSUE THREAD

**Issue by trek600** [angelk727/mir2#50]
这部分比较水晶原始代码应该是新增的,但是加载错了素材内容.
![image](https://github.com/user-attachments/assets/3f0f0dd8-1834-43e8-adee-de1c505e35b8)
代码位置为:
file : MLibrary.cs --> LoadGameLibraries() -->

**Comment by angelk727** [comment]
这好像是很久以前加的，都忘记了 。谢谢你的指正我会修复
