### ISSUE TITLE
关于Robot之中时区的问题

### ISSUE THREAD

**Issue by trek600** [angelk727/mir2#51]
由于我很早就使用cron表达式来替换了水晶默认的表达是,这是今天在删除垃圾代码的时候才发现的一个问题.
在Robot之中使用的UTC时间进行比较的,而我们处在东八区会有时区的问题.
实际我们在配置表达式的时候,总会按照本地时间进行配置,因此程序执行过程中就会有八小时的问题.
可以选择了在 Robot.cs ---> Process( ) --->  var matches = Robots.Where(x => x.IsMatch(Envir.Now.AddHours(8)));
手动添加了八小时来规避这个问题,最小化变更防止其它问题的出现.具体还有哪里,需要再仔细查询一下.

**Comment by angelk727** [comment]
我没有注意过这个问题
