### ISSUE TITLE
解决一次只能打开一个对话框的问题

### ISSUE THREAD

**Issue by benfang928** [angelk727/mir2#53]
建议把SMain.cs里的form.showdialog() 全换成form.show()
解决一次只能打开一个对话框的问题。
 private void nPCInfoToolStripMenuItem_Click(object sender, EventArgs e)
 {
     NPCInfoForm form = new NPCInfoForm();

     form.Show();
 }

**Comment by Jinspang** [comment]
头盔外显怎么写啊兄弟，天使他只按照官服写没办法....我想把我的老端加上外显。
我看客户端内的Client\Data\CHelmet目录里有三个外显，怎么写让他读这里面的外显？
在物品数据库【外观】那里对应Client\Data\CHelmet目录里的编号？
可以告知一下吗兄弟

**Comment by trek600** [comment]
头盔并没有外观素材,水晶之中没有对头盔进行过处理.
你可以尝试使用发型不分的代码进行模拟处理.
由于职业不同,头盔的素材并不通用,这也可能是一直不添加头盔外观的原因吧.

**Comment by Jinspang** [comment]
Client\Data\CHelmet  这个目录内不是吗

**Comment by trek600** [comment]
是的 代码之中没有任何任何处理.同样的应该有 Client\Data\AHelmet Client\Data\ARHelmet. 按照名称应该都是分职业动作的,和衣服武器一样,但是很不幸,里面并没有.

**Comment by Jinspang** [comment]
> 
好吧，感谢大哥了。
