### ISSUE TITLE
5.28bug报告

### ISSUE THREAD

**Issue by sddzrxh** [angelk727/mir2#6]
5.28BUG检查
1.魔法、道术、弓箭攻击，只要有树木、墙体、建筑物所有遮挡物攻击就失效。

2.英雄：除战士之外其他职业英雄攻击方式不对，只有战士是近身贴脸攻击，
其他职业“英雄”应该在玩家一定范围内移动，而英雄和怪物也保持一定范围走位攻击才对，
现在是所有职业都贴脸攻击。

3.物品信息：套装设置，只能选择默认套装，无法知晓套装属性， 
比如我选择《恶魔长袍+俩力量戒指》成为赤蓝套装，那么这是什么属性？不得而知。
（建议弄个套装详细设置，能更改套装的独立信息）
比如在功能里弄个套装设置，进去后自定义一个套装，或者更改现有的套装名称、配套物品、属性等。

4.称号系统，在称号LIB里固定出0-50是单张称号    51-150是动态称号（一般动态称号是几张一组？）（可在引擎增加功能自定义设置）

5.人物在选择页面进入游戏第一欢迎窗口没有。服务端Notice 文件内 

6.游戏内所有的输入框黑色背景底图都置顶了好像，例如商城搜索框，你把背包移过去，搜索框黑底就吧背包遮挡了（所有输入框都这样）

7.魔法锁定，现在只对怪物锁定，PK对人物不锁定，要一直拿鼠标对准人物。

8.聊天框上面的物品栏内，物品数字显示   把数字加个黑色描边这样显示的更清楚。

9。增加英雄装备持久显示框，

小地图下面增加 PING显示  攻击模式显示  技能模式

**Comment by sddzrxh** [comment]
把内挂改成这样呗？我把PSD传到盘里，你看看在原有基础上加了5个。
要弄的话别往里加图片，把原有的图替换掉就行，省的占地方越来越大。
https://www.123pan.com/s/eYRDjv-ORoe.html提取码:2hfh     PSD文件。
![QQ图片20240529000214](https://github.com/angelk727/mir2/assets/42303818/5902a37c-5280-4b66-b590-a3720ecfe243)

**Comment by angelk727** [comment]
GM创建行会是不要条件的，服务器配置-游戏系统-行会系统-创建栏可查看条件。可以留下你的邮箱地址

**Comment by sddzrxh** [comment]
> GM创建行会是不要条件的，服务器配置-游戏系统-行会系统-创建栏可查看条件。可以留下你的邮箱地址

13766977@qq.com
